[package]
name = "glide"
version = "0.1.0"
edition = "2021"

[lib]
name = "glide"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
rig-core = "0.22.0"
rig-helixdb = "0.1.1"