[project]
name = "glide"
version = "0.1.0"
description = "mcp server that tries to save you from git troubles"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.9.0",
    "fastmcp>=2.12.5",
    "python-dotenv>=1.1.1",
]
